config/routes.rb
Cnoofy::Application.routes.draw do

  devise_for :users

  get  '/new/:type', :to => 'posts#new', :as => :new_post
  
  resources :posts do
    resources :comments
  end

  resources :blogs do
    resources :posts
    match 'settings' => 'blogs#edit'
    match 'followers'
  end

  put    'like/:post_id' => 'likes#create',  :as => :like
  delete 'unlike/:post_id' => 'likes#destroy', :as => :unlike
  resources :likes, :controller => 'likes', :as => :likes

  put    'follow/:blog_id' => 'subscriptions#create',  :as => :follow
  delete 'unfollow/:blog_id' => 'subscriptions#destroy', :as => :unfollow
  resources :following, :controller => 'subscriptions', :as => :subscriptions

  get 'tagged/:tag', to: 'posts#index', as: :tag

  match '' => 'blogs#show_posts', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  authenticated :user do
    root :to => "posts#following"
  end

  devise_scope :user do
    get '/', :to => 'devise/registrations#new'
    match 'settings' => 'devise/registrations#edit', :as => :edit_user_registration
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :description, :subdomain, :title, :attachment

  has_many :posts
  has_many :subscriptions
  belongs_to :user

  mount_uploader :attachment, AttachmentUploader

  before_create :lowercase_subdomain
  
  def avatar(options = {:size => 50})
    if self.attachment_url
      version = 'square_' + options[:size].to_s
      img_url = self.attachment_url(version).to_s
    else
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      img_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{options[:size]}&d=monsterid"
    end
    ApplicationController.helpers.image_tag img_url
  end

  private
  def lowercase_subdomain
    self.subdomain.downcase!
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  load_and_authorize_resource
  
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog  = Blog.find_by_subdomain!(request.subdomain)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  def show_posts
    @blog  = Blog.find_by_subdomain!(request.subdomain)
    @posts = @blog.posts.order("created_at DESC")

    respond_to do |format|
      format.html { render :layout => 'blog' }
      format.json { render json: @blog }
    end
  end

  def followers
    @blog = Blog.find(params[:blog_id])
    @followers = Subscription.find_all_by_blog_id(@blog.id).map(&:user)
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:blog_id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to blog_settings_path(@blog), notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
  def blog_url(blog)
    root_url(:subdomain => blog.subdomain)
  end
end

app/views/blogs/_form.html.erb
<%= form_for @blog, :html => {:multipart => true} do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= @blog.avatar %></div>
  <div class="field">
    <%= f.label :attachment, 'Change avatar' %>
    <%= f.file_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :subdomain %>
    <%= f.text_field :subdomain %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/followers.html.erb
<h1><%= @blog.subdomain %> has <%= pluralize @followers.count, 'follower' %></h1>

<% if !@followers.empty? %>

  <ul>
    <% @followers.each do |follower| %>
    <li>
      <%= link_to follower.blogs.first.subdomain, blog_url(follower.blogs.first) %>
      <%= follow_button follower.blogs.first %>
    </li>
    <% end %>
  </ul>

<% else %>
  <p>This blog has no followers!</p>
<% end %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Subdomain</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.subdomain %></td>
    <td><%= blog.title %></td>
    <td><%= blog.description %></td>
    <td class="actions">
      <%= link_to 'Show', blog, :class => 'permalink' %>
      <%= link_to 'Edit', edit_blog_path(blog), :class => 'edit' %>
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'destroy' %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to 'New Blog', new_blog_path, :class => 'new blog' %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <b>Subdomain:</b>
  <%= @blog.subdomain %>
</p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Description:</b>
  <%= @blog.description %>
</p>

<div id="posts">
</div>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/show_posts.erb
<%= render "posts/list" %>