config/routes.rb
Cnoofy::Application.routes.draw do

  devise_for :users

  get  '/new/:type', :to => 'posts#new', :as => :new_post
  
  resources :posts do
    resources :comments
  end

  resources :blogs do
    resources :posts
    match 'settings' => 'blogs#edit'
    match 'followers'
  end

  put    'like/:post_id' => 'likes#create',  :as => :like
  delete 'unlike/:post_id' => 'likes#destroy', :as => :unlike
  resources :likes, :controller => 'likes', :as => :likes

  put    'follow/:blog_id' => 'subscriptions#create',  :as => :follow
  delete 'unfollow/:blog_id' => 'subscriptions#destroy', :as => :unfollow
  resources :following, :controller => 'subscriptions', :as => :subscriptions

  get 'tagged/:tag', to: 'posts#index', as: :tag

  match '' => 'blogs#show_posts', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  authenticated :user do
    root :to => "posts#following"
  end

  devise_scope :user do
    get '/', :to => 'devise/registrations#new'
    match 'settings' => 'devise/registrations#edit', :as => :edit_user_registration
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id

  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.order("created_at DESC")
  end

  def new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user_id = current_user.id

    if @comment.save
    respond_to do |format|
      format.json { render json: @post }
      format.html { redirect_to blog_post_path(@post.blog, @post), :notice => "Successfully saved." }
    end
    else
      render :action => 'new'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:post_id])
    @comment.destroy
    respond_to do |format|
      format.json { render json: @post }
      format.html { redirect_to blog_post_path(@post.blog, @post), :notice => "Successfully deleted comment." }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => "posts/single", :locals => {:post => @post} %>

  <div class="field">
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/comments/index.html.erb
<% @comments.each do |c| %>
  <%= c.user.blogs.first.avatar %>
  <%= c.user.blogs.first.subdomain %>
  <%= c.body %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_comments_path %>