config/routes.rb
Cnoofy::Application.routes.draw do

  devise_for :users

  get  '/new/:type', :to => 'posts#new', :as => :new_post
  
  resources :posts do
    resources :comments
  end

  resources :blogs do
    resources :posts
    match 'settings' => 'blogs#edit'
    match 'followers'
  end

  put    'like/:post_id' => 'likes#create',  :as => :like
  delete 'unlike/:post_id' => 'likes#destroy', :as => :unlike
  resources :likes, :controller => 'likes', :as => :likes

  put    'follow/:blog_id' => 'subscriptions#create',  :as => :follow
  delete 'unfollow/:blog_id' => 'subscriptions#destroy', :as => :unfollow
  resources :following, :controller => 'subscriptions', :as => :subscriptions

  get 'tagged/:tag', to: 'posts#index', as: :tag

  match '' => 'blogs#show_posts', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  authenticated :user do
    root :to => "posts#following"
  end

  devise_scope :user do
    get '/', :to => 'devise/registrations#new'
    match 'settings' => 'devise/registrations#edit', :as => :edit_user_registration
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :type, :body, :title, :tag_list, :attachment, :remote_attachment_url, :url, :quote_source
  
  belongs_to :blog
  has_many :likes
  has_many :comments
  
  acts_as_taggable
  mount_uploader :attachment, AttachmentUploader

  # Disable single table inheritance
  self.inheritance_column = nil

  before_validation :smart_add_url_protocol

  def chat_html
    lines = '<div class="chat-content">'
    body.lines.each { |line|
      line.gsub!(/(.*):(.*)/) {"<span class=\"speaker\">#{$1}:</span> #{$2}"}
      lines += '<div class="line">' + line + '</div>'
    }
    lines += '</div>'
    lines.html_safe
  end

  def embed_code
    begin
      oembed_response = OEmbed::Providers.get(url)
      oembed_response.html.html_safe
    rescue
      'Sorry, no media found!'
    end
  end

  validate :require_photo_source, :unless => Proc.new { type != 'photo' }
  private
  def require_photo_source
    if attachment.blank? && remote_attachment_url.blank?
      errors.add(:base, "Please specify at least one image")
    end
  end

  # Prepend URLs with "http://" if they don't already include a protocol
  # http://stackoverflow.com/a/7908693
  protected
  def smart_add_url_protocol
    unless self.url.nil? || self.url[/^http:\/\//] || self.url[/^https:\/\//]
      self.url = 'http://' + self.url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    if ( request[:blog_id] ) then
      @blog  = Blog.find(request[:blog_id])
      @posts = @blog.posts.order("created_at DESC")
      @title = "#{@blog.subdomain}'s Posts"
    elsif ( request[:tag] ) then
      @title = "Posts tagged '#{params[:tag]}'"
      @posts = Post.tagged_with(params[:tag]).order("created_at DESC")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def following
    @title = 'Dashboard'
    @posts = current_user.subscribed_posts
    @blog = current_user.blogs.first
    @is_dashboard = true
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @blog = Blog.find_by_subdomain(request.subdomain) || Blog.find(params[:blog_id])
    @post = @blog.posts.find(params[:id])

    respond_to do |format|
      format.html { render :layout => 'blog' }
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post.type = params[:type]
    @blog = current_user.blogs.first
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @blog = @post.blog
  end

  # POST /posts
  # POST /posts.json
  def create
    @blog = Blog.find(params[:blog_id])
    @post = Post.new(params[:post])
    @post.blog_id = @blog.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to blog_post_path(@blog, @post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @blog = @post.blog
    
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to [@blog, @post], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def permalink(post)
    post_url(post, :subdomain => post.blog.subdomain)
  end
end

app/views/posts/_form.html.erb
<%= form_for([@blog, @post], :url=>blog_posts_path(@blog)) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_list.html.erb
<div class="posts">
  <% @posts.each do |post| %>

    <%= render :partial => "posts/single", :locals => {:post => post} %>

  <% end %>
</div>

app/views/posts/_new_post_links.html.erb
<div class="new-post-links">
  <%= link_to 'Text', new_post_path(:text) %>
  <%= link_to 'Photo', new_post_path(:photo) %>
  <%= link_to 'Quote', new_post_path(:quote) %>
  <%= link_to 'Link', new_post_path(:link) %>
  <%= link_to 'Chat', new_post_path(:chat) %>
  <%= link_to 'Audio', new_post_path(:audio) %>
  <%= link_to 'Video', new_post_path(:video) %>
</div>

app/views/posts/_single.html.erb
<div class="post <%= post.type %>" id="post-<%= post.id %>">
  
  <%= link_to post.blog.avatar, blog_url(post.blog) %>

  <%= link_to post.blog.subdomain, blog_url(post.blog) %>
  
  <%= render :partial => "posts/single_content/#{post.type}", :locals => {:post => post} %>

  <% if !post.tag_list.empty? %>
    <div class="tags">Tagged: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></div>
  <% end %>

  <div class="actions">
    <%= link_to 'Show', permalink(post), :class => 'permalink' %>
    
    <% if (can? :like, post) %>
      / <%= like_button post %>
    <% end %>  

    <% if (can? :create, Comment) %>
      / <%= link_to 'Comment', new_post_comment_path(post) %>
    <% end %>

    <% if can? :update, post %>
       / <%= link_to 'Edit', edit_blog_post_path(post.blog, post), :class => 'edit' %>
    <% end %>

    <% if can? :destroy, post %>
      / <%= link_to 'Destroy', [post.blog, post], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'destroy' %>
    <% end %>

  </div>

</div>

app/views/posts/dashboard.html.erb
<h1><%= @title %></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Tags</th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.tags %></td>
    <td class="actions">
      <%= link_to 'Show', [post.blog, post], :class => 'show' %>
      <%= link_to 'Edit', edit_blog_post_path(post.blog, post), :class => 'edit' %>
      <%= link_to 'Destroy', [post.blog, post], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'destroy' %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to 'New Post', new_blog_post_path(:blog_id => current_user.blogs.first), :class => 'new post' %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "posts/forms/#{@post.type}" %>

<%= link_to 'Show', [@post.blog, @post] %> |
<%= link_to 'Back', blog_posts_path %>

app/views/posts/index.html.erb
<h1><%= @title %></h1>

<%= render 'new_post_links' %>

<% if @is_dashboard && current_user.subscribed_blogs.count <= 0 %>
  <div class="welcome">
    <h2>Welcome to the dashboard!</h2>
    <p>This is where all the posts of the blogs you follow would go... IF YOU HAD ANY!</p>
    <p>Why don't you try following one of these swell blogs?</p>
    <ul class="featured">
      <% User.with_role(:featured).each do |u| %>
        <li>
          <%= link_to(u.blogs.first.avatar({:size => 100}), blog_url(u.blogs.first), :class => :avatar) %>
          <%= link_to(u.blogs.first.subdomain, blog_url(u.blogs.first), :class => :subdomain) %>
          <%= follow_button u.blogs.first %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'list' %>

app/views/posts/new.html.erb
<h1>New <%= @post.type.titleize %></h1>

<%= render "posts/forms/#{@post.type}" %>

<%= link_to 'Back', blog_posts_path(@blog) %>

app/views/posts/show.html.erb
<%= render :partial => "posts/single", :locals => {:post => @post} %>

<h3>Comments</h3>

<% if @post.comments.length > 0 %>
<ul class="comments">
  <% @post.comments.each do |c| %>
    <li>
      <%= link_to( c.user.blogs.first.avatar({:size => 25}) + c.user.blogs.first.subdomain, blog_url(c.user.blogs.first) ) %> said: <%= c.body %>
    </li>
  <% end %>
</ul>

<% else %>

<p>No comments yet. <%= link_to 'Be the first!', new_post_comment_path(@post) %></p>

<% end %>

app/views/posts/table.html.erb
<h1><%= @title %></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.tags %></td>
    <td class="actions">
      <%= link_to 'Show', [post.blog, post], :class => 'permalink' %>
      <%= link_to 'Edit', edit_blog_post_path(post.blog, post), :class => 'edit' %>
      <%= link_to 'Destroy', [post.blog, post], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'destroy' %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to 'New Post', new_blog_post_path, :class => 'new post' %>